'use strict'
const EventedSet = require('../../lib/EventedSet.js')
const EventedSetOfSets = require('../../lib/EventedSetOfSets.js')
const tape = require('tape')

tape('basic op', t => {
  const set = new EventedSet()
  set.add('x')
  set.add('y')
  const set2 = new EventedSet()
  set2.add('y')
  set2.add('z')
  const combined = new EventedSetOfSets()
  combined.add(set)
  t.ok(combined.has('x'))
  t.ok(combined.has('y'))
  combined.add(set2)
  t.ok(combined.has('z'))
  t.equals(combined.size, 3)
  combined.delete(set)
  t.ok(!combined.has('x'))
  t.ok(combined.has('y'))
  t.ok(combined.has('z'))
  t.equals(combined.size, 2)
  combined.add(set2)
  t.ok(!combined.has('x'))
  t.ok(combined.has('y'))
  t.ok(combined.has('z'))
  t.end()
})

tape('events', t => {
  const set = new EventedSet()
  set.add('x')

  const combined = new EventedSetOfSets()
  const stack = []
  combined.on('add', entry => stack.push({ add: entry }))
  combined.on('delete', entry => stack.push({ delete: entry }))
  combined.add(set)
  t.deepEquals(stack, [{ add: 'x' }])
  set.add('y')
  t.deepEquals(stack, [{ add: 'x' }, { add: 'y' }])
  const set2 = new EventedSet()
  combined.add(set2)
  set2.add('y')
  t.deepEquals(stack, [{ add: 'x' }, { add: 'y' }])
  combined.delete(set)
  t.deepEquals(stack, [{ add: 'x' }, { add: 'y' }, { delete: 'x' }])
  t.end()
})
